# Generated by Django 3.1.3 on 2021-12-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0003_jobprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobprofile',
            old_name='job_profile',
            new_name='job_profile_name',
        ),
    ]
