# Generated by Django 3.1.3 on 2021-12-27 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobportalapp', '0004_auto_20211227_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateform',
            name='jobProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobportalapp.jobprofile'),
        ),
        migrations.AddField(
            model_name='candidateform',
            name='pdf_CV',
            field=models.FileField(blank=True, null=True, upload_to='static/pdf'),
        ),
    ]
