# Generated by Django 4.1.4 on 2023-03-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobportalapp", "0005_auto_20211227_2027"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateform",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="jobprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
