# Generated by Django 4.1.4 on 2023-03-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobportalapp", "0006_alter_candidateform_id_alter_customuser_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="email",
            new_name="mail",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="username",
            new_name="password",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="mobile_number",
        ),
    ]
