# Generated by Django 4.1.4 on 2023-03-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobportalapp", "0007_rename_email_customuser_mail_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="password",
            new_name="user_name",
        ),
    ]
